# Generated by Django 2.2.4 on 2019-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_urls',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
