# Generated by Django 2.2.4 on 2019-11-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20191123_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_urls',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
