# Generated by Django 2.2.4 on 2019-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20191125_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_urls',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
