# Generated by Django 2.2.4 on 2019-12-09 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20191209_1831'),
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributes',
            name='urls',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='calc.Courses'),
            preserve_default=False,
        ),
    ]
