# Generated by Django 2.2.4 on 2019-12-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20191209_1831'),
        ('contribution', '0005_remove_contributes_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributes',
            name='urls',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calc.Courses'),
        ),
    ]
