# Generated by Django 2.2.4 on 2019-12-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0009_contributes_cont_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributes',
        ),
    ]
